---
title: "MA 615 Final Project"
author: "Weixiao Li"
date: "`r Sys.Date()`"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(readr)
library(ggplot2)
```


```{r}
TRAVEL <- read.csv("D:/360Downloads/Travel_Times_2021/HRTravelTimesQ4_21.csv")
```

# November 2021
```{r}
Travel <- dplyr::filter(TRAVEL,service_date==	"2021-11-14"|service_date==	"2021-11-15"|service_date==	"2021-11-16"|service_date==	"2021-11-17"|service_date==	"2021-11-18"|service_date==	"2021-11-19"|service_date==	"2021-11-20"|service_date==
"2021-11-21")
nTravel <- dplyr::filter(Travel,route_id=="Orange")
```

##1 The earliest train on the Orange Line that runs the full distance

```{r}
m <- dplyr::filter(nTravel,service_date=="2021-11-15")
m1 <- dplyr::filter(m,direction_id==0)
m2<- dplyr::filter(m1,to_stop_id==min(m1$to_stop_id))
m3 <- dplyr::filter(m2,end_time_sec==min(m2$end_time_sec))
m4<-dplyr::arrange(m3,travel_time_sec)
```


```{r}
f15 <- max(m4$travel_time_sec)
m16 <- dplyr::filter(nTravel,service_date=="2021-11-16")
m16_1 <- dplyr::filter(m16,direction_id==0)
m16_2<- dplyr::filter(m16_1,to_stop_id==min(m16_1$to_stop_id))
m16_3 <- dplyr::filter(m16_2,end_time_sec==min(m16_2$end_time_sec))
m16_4<-dplyr::arrange(m16_3,travel_time_sec)
f16 <- max(m16_4$travel_time_sec)

m17 <- dplyr::filter(nTravel,service_date=="2021-11-17")
m17_1 <- dplyr::filter(m17,direction_id==0)
m17_2<- dplyr::filter(m17_1,to_stop_id==min(m17_1$to_stop_id))
m17_3 <- dplyr::filter(m17_2,end_time_sec==min(m17_2$end_time_sec))
m17_4<-dplyr::arrange(m17_3,travel_time_sec)
f17 <- max(m17_4$travel_time_sec)

m18 <- dplyr::filter(nTravel,service_date=="2021-11-18")
m18_1 <- dplyr::filter(m18,direction_id==0)
m18_2<- dplyr::filter(m18_1,to_stop_id==min(m18_1$to_stop_id))
m18_3 <- dplyr::filter(m18_2,end_time_sec==min(m18_2$end_time_sec))
m18_4<-dplyr::arrange(m18_3,travel_time_sec)
f18 <- max(m18_4$travel_time_sec)

m19 <- dplyr::filter(nTravel,service_date=="2021-11-19")
m19_1 <- dplyr::filter(m19,direction_id==0)
m19_2<- dplyr::filter(m19_1,to_stop_id==min(m19_1$to_stop_id))
m19_3 <- dplyr::filter(m19_2,end_time_sec==min(m19_2$end_time_sec))
m19_4<-dplyr::arrange(m19_3,travel_time_sec)
f19 <- max(m19_4$travel_time_sec)

m20 <- dplyr::filter(nTravel,service_date=="2021-11-20")
m20_1 <- dplyr::filter(m20,direction_id==0)
m20_2<- dplyr::filter(m20_1,to_stop_id==min(m20_1$to_stop_id))
m20_3 <- dplyr::filter(m20_2,end_time_sec==min(m20_2$end_time_sec))
m20_4<-dplyr::arrange(m20_3,travel_time_sec)
f20 <- max(m20_4$travel_time_sec)

m21 <- dplyr::filter(nTravel,service_date=="2021-11-21")
m21_1 <- dplyr::filter(m21,direction_id==0)
m21_2<- dplyr::filter(m21_1,to_stop_id==min(m21_1$to_stop_id))
m21_3 <- dplyr::filter(m21_2,end_time_sec==min(m21_2$end_time_sec))
m21_4<-dplyr::arrange(m21_3,travel_time_sec)
f21 <- max(m21_4$travel_time_sec)
```

```{r}
total_time <- c(f15,f16,f17,f18,f19,f20,f21)
date <- c("11-15","11-16","11-17","11-18","11-19","11-20","11-21")
df_2 <- data.frame(x = date, y = total_time)
ggplot(data = df_2, aes(x = date, y = total_time )) + geom_line(aes(x,y,group=1),col="lightblue")+geom_point(aes(x,y),col="purple")

```

## 2 The earliest train on the Orange Line, arriving at each station
```{r}
d15 <- diff(m4$travel_time_sec)
d16 <- diff(m16_4$travel_time_sec)
d17 <- diff(m17_4$travel_time_sec)
d18 <- diff(m18_4$travel_time_sec)
d19 <- diff(m19_4$travel_time_sec)
d20 <- diff(m20_4$travel_time_sec)
d21 <- diff(m21_4$travel_time_sec)
```

```{r}
date <- c("11-15","11-16","11-17","11-18","11-19","11-20","11-21")
diff <- data.frame(d15,d16,d17,d18,d19,d20,d21)
ggplot()+geom_line(data = diff,aes(y = diff$d15,colour = "d15"),size=1)+
  geom_point(data =  diff,aes(y = diff$d15,colour = "d15"),size=3)+
  geom_line(data =  diff,aes(y = diff$d16,colour = "d16"),size=1) + 
  geom_point(data =  diff,aes(y = diff$d16,colour = "d16"),size=3)+
  geom_line(data =  diff,aes(y = diff$d17,colour = "d17"),size=1) + 
  geom_point(data =  diff,aes(y = diff$d17,colour = "d17"),size=3)+
  geom_line(data =  diff,aes(y = diff$d18,colour = "d18"),size=1) + 
  geom_point(data =  diff,aes(y = diff$d18,colour = "d18"),size=3)+
  geom_line(data =  diff,aes(y = diff$d19,colour = "d19"),size=1) + 
  geom_point(data =  diff,aes(y = diff$d19,colour = "d19"),size=3)+
  geom_line(data =  diff,aes(y = diff$d20,colour = "d20"),size=1) + 
  geom_point(data =  diff,aes(y = diff$d20,colour = "d20"),size=3)+
  geom_line(data =  diff,aes(y = diff$d21,colour = "d21"),size=1) + 
  geom_point(data =  diff,aes(y = diff$d21,colour = "d21"),size=3)
  scale_colour_manual("",values = c("d15" = "red","d16" = "green","d17"="yellow","d18"="pink","d19"="black","d20"="orange","d21"="blue"),)
```



##3 Mean of total time that runs the full distance

```{r}
t <- dplyr::filter(nTravel,from_stop_id==min(nTravel$from_stop_id)& to_stop_id==max(nTravel$to_stop_id))
t15 <- dplyr::filter(t,service_date=="2021-11-15")
t16 <- dplyr::filter(t,service_date=="2021-11-16")
t17 <- dplyr::filter(t,service_date=="2021-11-17")
t18 <- dplyr::filter(t,service_date=="2021-11-18")
t19 <- dplyr::filter(t,service_date=="2021-11-19")
t20 <- dplyr::filter(t,service_date=="2021-11-20")
t21 <- dplyr::filter(t,service_date=="2021-11-21")
travel_time <- c(mean(t15$travel_time_sec),mean(t16$travel_time_sec),mean(t17$travel_time_sec),mean(t18$travel_time_sec),mean(t19$travel_time_sec),mean(t20$travel_time_sec),mean(t21$travel_time_sec))
date <- c("11-15","11-16","11-17","11-18","11-19","11-20","11-21")
df_1 <- data.frame(x = date, y = travel_time)
ggplot(data = df_1, mapping = aes(x = travel_time, y = date)) + geom_bar(stat="identity",fill="lightblue")+ggtitle("From 70001 to 70279")
```

##December2021
```{r}
Travel_dec <- dplyr::filter(TRAVEL,service_date==	"2021-12-15"|service_date==	"2021-12-16"|service_date==	"2021-12-17"|service_date==	"2021-12-18"|service_date==	"2021-12-19"|service_date==	"2021-12-20"|service_date==
"2021-12-21")
nTravel_dec <- dplyr::filter(Travel_dec,route_id=="Orange")
```

## 1

```{r}
d15 <- dplyr::filter(nTravel_dec,service_date=="2021-12-15")
d15_1 <- dplyr::filter(d15,direction_id==0)
d15_2<- dplyr::filter(d15_1,to_stop_id==min(d15_1$to_stop_id))
d15_3 <- dplyr::filter(d15_2,end_time_sec==min(d15_2$end_time_sec))
d15_4<-dplyr::arrange(d15_3,travel_time_sec)
d15 <- max(d15_4$travel_time_sec)

d16 <- dplyr::filter(nTravel_dec,service_date=="2021-12-16")
d16_1 <- dplyr::filter(d16,direction_id==0)
d16_2<- dplyr::filter(d16_1,to_stop_id==min(d16_1$to_stop_id))
d16_3 <- dplyr::filter(d16_2,end_time_sec==min(d16_2$end_time_sec))
d16_4<-dplyr::arrange(d16_3,travel_time_sec)
d16 <- max(d16_4$travel_time_sec)

d17 <- dplyr::filter(nTravel_dec,service_date=="2021-12-17")
d17_1 <- dplyr::filter(d17,direction_id==0)
d17_2<- dplyr::filter(d17_1,to_stop_id==min(d17_1$to_stop_id))
d17_3 <- dplyr::filter(d17_2,end_time_sec==min(d17_2$end_time_sec))
d17_4<-dplyr::arrange(d17_3,travel_time_sec)
d17 <- max(d17_4$travel_time_sec)

d18 <- dplyr::filter(nTravel_dec,service_date=="2021-12-18")
d18_1 <- dplyr::filter(d18,direction_id==0)
d18_2<- dplyr::filter(d18_1,to_stop_id==min(d18_1$to_stop_id))
d18_3 <- dplyr::filter(d18_2,end_time_sec==min(d18_2$end_time_sec))
d18_4<-dplyr::arrange(d18_3,travel_time_sec)
d18 <- max(d18_4$travel_time_sec)

d19 <- dplyr::filter(nTravel_dec,service_date=="2021-12-19")
d19_1 <- dplyr::filter(d19,direction_id==0)
d19_2<- dplyr::filter(d19_1,to_stop_id==min(d19_1$to_stop_id))
d19_3 <- dplyr::filter(d19_2,end_time_sec==min(d19_2$end_time_sec))
d19_4<-dplyr::arrange(d19_3,travel_time_sec)
d19 <- max(d19_4$travel_time_sec)

d20 <- dplyr::filter(nTravel_dec,service_date=="2021-12-20")
d20_1 <- dplyr::filter(d20,direction_id==0)
d20_2<- dplyr::filter(d20_1,to_stop_id==min(d20_1$to_stop_id))
d20_3 <- dplyr::filter(d20_2,end_time_sec==min(d20_2$end_time_sec))
d20_4<-dplyr::arrange(d20_3,travel_time_sec)
d20 <- max(d20_4$travel_time_sec)

d21 <- dplyr::filter(nTravel_dec,service_date=="2021-12-21")
d21_1 <- dplyr::filter(d21,direction_id==0)
d21_2<- dplyr::filter(d21_1,to_stop_id==min(d21_1$to_stop_id))
d21_3 <- dplyr::filter(d21_2,end_time_sec==min(d21_2$end_time_sec))
d21_4<-dplyr::arrange(d21_3,travel_time_sec)
d21 <- max(d21_4$travel_time_sec)
```

```{r}
total_time_dec <- c(d15,d16,d17,d18,d19,d20,d21)
Dec <- c("12-15","12-16","12-17","12-18","12-19","12-20","12-21")
df_2_dec <- data.frame(x = Dec, y = total_time_dec)
ggplot(data = df_2_dec, aes(x = Dec, y = total_time_dec )) + geom_line(aes(x,y,group=1),col="lightblue")+geom_point(aes(x,y),col="purple")
```

#2
```{r}
di15 <- diff(d15_4$travel_time_sec)
di16 <- diff(d16_4$travel_time_sec)
di17 <- diff(d17_4$travel_time_sec)
di18 <- diff(d18_4$travel_time_sec)
di19 <- diff(d19_4$travel_time_sec)
di20 <- diff(d20_4$travel_time_sec)
di21 <- diff(d21_4$travel_time_sec)
```

#3
```{r}
t_dec <- dplyr::filter(nTravel_dec,from_stop_id==min(nTravel_dec$from_stop_id)& to_stop_id==max(nTravel_dec$to_stop_id))
t15_dec <- dplyr::filter(t_dec,service_date=="2021-12-15")
t16_dec <- dplyr::filter(t_dec,service_date=="2021-12-16")
t17_dec <- dplyr::filter(t_dec,service_date=="2021-12-17")
t18_dec <- dplyr::filter(t_dec,service_date=="2021-12-18")
t19_dec <- dplyr::filter(t_dec,service_date=="2021-12-19")
t20_dec<- dplyr::filter(t_dec,service_date=="2021-12-20")
t21_dec<- dplyr::filter(t_dec,service_date=="2021-12-21")
travel_time_dec <- c(mean(t15_dec$travel_time_sec),mean(t16_dec$travel_time_sec),mean(t17_dec$travel_time_sec),mean(t18_dec$travel_time_sec),mean(t19_dec$travel_time_sec),mean(t20_dec$travel_time_sec),mean(t21_dec$travel_time_sec))
Dec <- c("12-15","12-16","12-17","12-18","12-19","12-20","12-21")
df_1_dec <- data.frame(x = Dec, y = travel_time_dec)
ggplot(data = df_1_dec, mapping = aes(x = travel_time_dec, y = Dec)) + geom_bar(stat="identity",fill="lightblue")+ggtitle("From Start to Finish")
```

# January
```{r}
TRAVEL2022 <- read.csv("D:/360Downloads/TravelTimes_2022/TravelTimes_2022/2022-Q1_HRTravelTimes.csv")
Travel_jan <- dplyr::filter(TRAVEL2022 ,service_date==	"2022-01-15"|service_date==	"2022-01-16"|service_date==	"2022-01-17"|service_date==	"2022-01-18"|service_date==	"2022-01-19"|service_date==	"2022-01-20"|service_date==
"2022-01-21")
nTravel_jan <- dplyr::filter(Travel_jan,route_id=="Orange")
```

#1
```{r}
j15 <- dplyr::filter(nTravel_jan,service_date=="2022-01-15")
j15_1 <- dplyr::filter(j15,direction_id==0)
j15_2<- dplyr::filter(j15_1,to_stop_id==min(j15_1$to_stop_id))
j15_3 <- dplyr::filter(j15_2,end_time_sec==min(j15_2$end_time_sec))
j15_4<-dplyr::arrange(j15_3,travel_time_sec)
j15 <- max(j15_4$travel_time_sec)

j16 <- dplyr::filter(nTravel_jan,service_date=="2022-01-16")
j16_1 <- dplyr::filter(j16,direction_id==0)
j16_2<- dplyr::filter(j16_1,to_stop_id==min(j16_1$to_stop_id))
j16_3 <- dplyr::filter(j16_2,end_time_sec==min(j16_2$end_time_sec))
j16_4<-dplyr::arrange(j16_3,travel_time_sec)
j16 <- max(j16_4$travel_time_sec)

j17 <- dplyr::filter(nTravel_jan,service_date=="2022-01-17")
j17_1 <- dplyr::filter(j17,direction_id==0)
j17_2<- dplyr::filter(j17_1,to_stop_id==min(j17_1$to_stop_id))
j17_3 <- dplyr::filter(j17_2,end_time_sec==min(j17_2$end_time_sec))
j17_4<-dplyr::arrange(j17_3,travel_time_sec)
j17 <- max(j17_4$travel_time_sec)

j18 <- dplyr::filter(nTravel_jan,service_date=="2022-01-18")
j18_1 <- dplyr::filter(j18,direction_id==0)
j18_2<- dplyr::filter(j18_1,to_stop_id==min(j18_1$to_stop_id))
j18_3 <- dplyr::filter(j18_2,end_time_sec==min(j18_2$end_time_sec))
j18_4<-dplyr::arrange(j18_3,travel_time_sec)
j18 <- max(j18_4$travel_time_sec)

j19 <- dplyr::filter(nTravel_jan,service_date=="2022-01-19")
j19_1 <- dplyr::filter(j19,direction_id==0)
j19_2<- dplyr::filter(j19_1,to_stop_id==min(j19_1$to_stop_id))
j19_3 <- dplyr::filter(j19_2,end_time_sec==min(j19_2$end_time_sec))
j19_4<-dplyr::arrange(j19_3,travel_time_sec)
j19 <- max(j19_4$travel_time_sec)

j20 <- dplyr::filter(nTravel_jan,service_date=="2022-01-20")
j20_1 <- dplyr::filter(j20,direction_id==0)
j20_2<- dplyr::filter(j20_1,to_stop_id==min(j20_1$to_stop_id))
j20_3 <- dplyr::filter(j20_2,end_time_sec==min(j20_2$end_time_sec))
j20_4<-dplyr::arrange(j20_3,travel_time_sec)
j20 <- max(j20_4$travel_time_sec)

j21 <- dplyr::filter(nTravel_jan,service_date=="2022-01-21")
j21_1 <- dplyr::filter(j21,direction_id==0)
j21_2<- dplyr::filter(j21_1,to_stop_id==min(j21_1$to_stop_id))
j21_3 <- dplyr::filter(j21_2,end_time_sec==min(j21_2$end_time_sec))
j21_4<-dplyr::arrange(j21_3,travel_time_sec)
j21 <- max(j21_4$travel_time_sec)
```

```{r}
total_time_jan<- c(j15,j16,j17,j18,j19,j20,j21)
Jan <- c("1-15","1-16","1-17","1-18","1-19","1-20","1-21")
df_2_jan <- data.frame(x = Jan, y = total_time_jan)
ggplot(data = df_2_jan, aes(x = Jan, y = total_time_jan )) + geom_line(aes(x,y,group=1),col="lightblue")+geom_point(aes(x,y),col="purple")
```

#2
```{r}
di15_jan <- diff(j15_4$travel_time_sec)
di16_jan <- diff(j16_4$travel_time_sec)
di17_jan <- diff(j17_4$travel_time_sec)
di18_jan <- diff(j18_4$travel_time_sec)
di19_jan <- diff(j19_4$travel_time_sec)
di20_jan <- diff(j20_4$travel_time_sec)
di21_jan <- diff(j21_4$travel_time_sec)
```

#3
```{r}
t_jan <- dplyr::filter(nTravel_jan,from_stop_id==min(nTravel_jan$from_stop_id)& to_stop_id==max(nTravel_jan$to_stop_id))
t15_jan <- dplyr::filter(t_jan,service_date=="2022-01-15")
t16_jan <- dplyr::filter(t_jan,service_date=="2022-01-16")
t17_jan <- dplyr::filter(t_jan,service_date=="2022-01-17")
t18_jan <- dplyr::filter(t_jan,service_date=="2022-01-18")
t19_jan <- dplyr::filter(t_jan,service_date=="2022-01-19")
t20_jan<- dplyr::filter(t_jan,service_date=="2022-01-20")
t21_jan<- dplyr::filter(t_jan,service_date=="2022-01-21")
travel_time_jan <- c(mean(t15_jan$travel_time_sec),mean(t16_jan$travel_time_sec),mean(t17_jan$travel_time_sec),mean(t18_jan$travel_time_sec),mean(t19_jan$travel_time_sec),mean(t20_jan$travel_time_sec),mean(t21_jan$travel_time_sec))
df_1_jan <- data.frame(x = Jan, y = travel_time_jan)
ggplot(data = df_1_jan, mapping = aes(x = travel_time_jan, y = Jan)) + geom_bar(stat="identity",fill="lightblue")+ggtitle("From Start to Finish")
```

# Feb
```{r}
Travel_feb <- dplyr::filter(TRAVEL2022 ,service_date==	"2022-02-15"|service_date==	"2022-02-16"|service_date==	"2022-02-17"|service_date==	"2022-02-18"|service_date==	"2022-02-19"|service_date==	"2022-02-20"|service_date==
"2022-02-21")
nTravel_feb <- dplyr::filter(Travel_feb,route_id=="Orange")
```

#1
```{r}
f15 <- dplyr::filter(nTravel_feb,service_date=="2022-02-15")
f15_1 <- dplyr::filter(f15,direction_id==0)
f15_2<- dplyr::filter(f15_1,to_stop_id==min(f15_1$to_stop_id))
f15_3 <- dplyr::filter(f15_2,end_time_sec==min(f15_2$end_time_sec))
f15_4<-dplyr::arrange(f15_3,travel_time_sec)
f15 <- max(f15_4$travel_time_sec)

f16 <- dplyr::filter(nTravel_feb,service_date=="2022-02-16")
f16_1 <- dplyr::filter(f16,direction_id==0)
f16_2<- dplyr::filter(f16_1,to_stop_id==min(f16_1$to_stop_id))
f16_3 <- dplyr::filter(f16_2,end_time_sec==min(f16_2$end_time_sec))
f16_4<-dplyr::arrange(f16_3,travel_time_sec)
f16 <- max(f16_4$travel_time_sec)

f17 <- dplyr::filter(nTravel_feb,service_date=="2022-02-17")
f17_1 <- dplyr::filter(f17,direction_id==0)
f17_2<- dplyr::filter(f17_1,to_stop_id==min(f17_1$to_stop_id))
f17_3 <- dplyr::filter(f17_2,end_time_sec==min(f17_2$end_time_sec))
f17_4<-dplyr::arrange(f17_3,travel_time_sec)
f17 <- max(f17_4$travel_time_sec)

f18 <- dplyr::filter(nTravel_feb,service_date=="2022-02-18")
f18_1 <- dplyr::filter(f18,direction_id==0)
f18_2<- dplyr::filter(f18_1,to_stop_id==min(f18_1$to_stop_id))
f18_3 <- dplyr::filter(f18_2,end_time_sec==min(f18_2$end_time_sec))
f18_4<-dplyr::arrange(f18_3,travel_time_sec)
f18 <- max(f18_4$travel_time_sec)

f19<- dplyr::filter(nTravel_feb,service_date=="2022-02-19")
f19_1 <- dplyr::filter(f19,direction_id==0)
f19_2<- dplyr::filter(f19_1,to_stop_id==min(f19_1$to_stop_id))
f19_3 <- dplyr::filter(f19_2,end_time_sec==min(f19_2$end_time_sec))
f19_4<-dplyr::arrange(f19_3,travel_time_sec)
f19 <- max(f19_4$travel_time_sec)

f20 <- dplyr::filter(nTravel_feb,service_date=="2022-02-20")
f20_1 <- dplyr::filter(f20,direction_id==0)
f20_2<- dplyr::filter(f20_1,to_stop_id==min(f20_1$to_stop_id))
f20_3 <- dplyr::filter(f20_2,end_time_sec==min(f20_2$end_time_sec))
f20_4<-dplyr::arrange(f20_3,travel_time_sec)
f20 <- max(f20_4$travel_time_sec)

f21 <- dplyr::filter(nTravel_feb,service_date=="2022-02-21")
f21_1 <- dplyr::filter(f21,direction_id==0)
f21_2<- dplyr::filter(f21_1,to_stop_id==min(f21_1$to_stop_id))
f21_3 <- dplyr::filter(f21_2,end_time_sec==min(f21_2$end_time_sec))
f21_4<-dplyr::arrange(f21_3,travel_time_sec)
f21 <- max(f21_4$travel_time_sec)

```

```{r}
total_time_feb<- c(f15,f16,f17,f18,f19,f20,f21)
Feb <- c("2-15","2-16","2-17","2-18","2-19","2-20","2-21")
df_2_feb <- data.frame(x = Feb, y = total_time_feb)
ggplot(data = df_2_feb, aes(x = Feb, y = total_time_feb )) + geom_line(aes(x,y,group=1),col="lightblue")+geom_point(aes(x,y),col="purple")
```

#3
```{r}
t_jan <- dplyr::filter(nTravel_jan,from_stop_id==min(nTravel_jan$from_stop_id)& to_stop_id==max(nTravel_jan$to_stop_id))
t15_jan <- dplyr::filter(t_jan,service_date=="2022-01-15")
t16_jan <- dplyr::filter(t_jan,service_date=="2022-01-16")
t17_jan <- dplyr::filter(t_jan,service_date=="2022-01-17")
t18_jan <- dplyr::filter(t_jan,service_date=="2022-01-18")
t19_jan <- dplyr::filter(t_jan,service_date=="2022-01-19")
t20_jan<- dplyr::filter(t_jan,service_date=="2022-01-20")
t21_jan<- dplyr::filter(t_jan,service_date=="2022-01-21")
travel_time_jan <- c(mean(t15_jan$travel_time_sec),mean(t16_jan$travel_time_sec),mean(t17_jan$travel_time_sec),mean(t18_jan$travel_time_sec),mean(t19_jan$travel_time_sec),mean(t20_jan$travel_time_sec),mean(t21_jan$travel_time_sec))
df_1_jan <- data.frame(x = Jan, y = travel_time_jan)
ggplot(data = df_1_jan, mapping = aes(x = travel_time_jan, y = Jan)) + geom_bar(stat="identity",fill="lightblue")+ggtitle("From Start to Finish")
```

# Mar

```{r}
Travel_mar <- dplyr::filter(TRAVEL2022 ,service_date==	"2022-03-15"|service_date==	"2022-03-16"|service_date==	"2022-03-17"|service_date==	"2022-03-18"|service_date==	"2022-03-19"|service_date==	"2022-03-20"|service_date==
"2022-03-21")
nTravel_mar <- dplyr::filter(Travel_mar,route_id=="Orange")
```

#1
```{r}
m15 <- dplyr::filter(nTravel_mar,service_date=="2022-03-15")
m15_1 <- dplyr::filter(m15,direction_id==0)
m15_2<- dplyr::filter(m15_1,to_stop_id==min(m15_1$to_stop_id))
m15_3 <- dplyr::filter(m15_2,end_time_sec==min(m15_2$end_time_sec))
m15_4<-dplyr::arrange(m15_3,travel_time_sec)
m15 <- max(m15_4$travel_time_sec)

m16 <- dplyr::filter(nTravel_mar,service_date=="2022-03-16")
m16_1 <- dplyr::filter(m16,direction_id==0)
m16_2<- dplyr::filter(m16_1,to_stop_id==min(m16_1$to_stop_id))
m16_3 <- dplyr::filter(m16_2,end_time_sec==min(m16_2$end_time_sec))
m16_4<-dplyr::arrange(m16_3,travel_time_sec)
m16 <- max(m16_4$travel_time_sec)

m17 <- dplyr::filter(nTravel_mar,service_date=="2022-03-17")
m17_1 <- dplyr::filter(m17,direction_id==0)
m17_2<- dplyr::filter(m17_1,to_stop_id==min(m17_1$to_stop_id))
m17_3 <- dplyr::filter(m17_2,end_time_sec==min(m17_2$end_time_sec))
m17_4<-dplyr::arrange(m17_3,travel_time_sec)
m17 <- max(m17_4$travel_time_sec)

m18 <- dplyr::filter(nTravel_mar,service_date=="2022-03-18")
m18_1 <- dplyr::filter(m18,direction_id==0)
m18_2<- dplyr::filter(m18_1,to_stop_id==min(m18_1$to_stop_id))
m18_3 <- dplyr::filter(m18_2,end_time_sec==min(m18_2$end_time_sec))
m18_4<-dplyr::arrange(m18_3,travel_time_sec)
m18 <- max(m18_4$travel_time_sec)

m19 <- dplyr::filter(nTravel_mar,service_date=="2022-03-19")
m19_1 <- dplyr::filter(m19,direction_id==0)
m19_2<- dplyr::filter(m19_1,to_stop_id==min(m19_1$to_stop_id))
m19_3 <- dplyr::filter(m19_2,end_time_sec==min(m19_2$end_time_sec))
m19_4<-dplyr::arrange(m19_3,travel_time_sec)
m19 <- max(m19_4$travel_time_sec)

m20 <- dplyr::filter(nTravel_mar,service_date=="2022-03-20")
m20_1 <- dplyr::filter(m20,direction_id==0)
m20_2<- dplyr::filter(m20_1,to_stop_id==min(m20_1$to_stop_id))
m20_3 <- dplyr::filter(m20_2,end_time_sec==min(m20_2$end_time_sec))
m20_4<-dplyr::arrange(m20_3,travel_time_sec)
m20 <- max(m20_4$travel_time_sec)

m21 <- dplyr::filter(nTravel_mar,service_date=="2022-03-21")
m21_1 <- dplyr::filter(m21,direction_id==0)
m21_2<- dplyr::filter(m21_1,to_stop_id==min(m21_1$to_stop_id))
m21_3 <- dplyr::filter(m21_2,end_time_sec==min(m21_2$end_time_sec))
m21_4<-dplyr::arrange(m21_3,travel_time_sec)
m21 <- max(m21_4$travel_time_sec)
```

```{r}
total_time_mar<- c(m15,m16,m17,m18,m19,m20,m21)
Mar <- c("3-15","3-16","3-17","3-18","3-19","3-20","3-21")
df_2_mar <- data.frame(x = Mar, y = total_time_mar)
ggplot(data = df_2_mar, aes(x = Mar, y = total_time_mar )) + geom_line(aes(x,y,group=1),col="lightblue")+geom_point(aes(x,y),col="purple")
```
# April
```{r}
HRQ2 <- read.csv("D:/360Downloads/TravelTimes_2022/TravelTimes_2022/2022-Q2_HRTravelTimes.csv")
```

```{r}
Travel_apr <- dplyr::filter(HRQ2 ,service_date==	"2022-04-15"|service_date==	"2022-04-16"|service_date==	"2022-04-17"|service_date==	"2022-04-18"|service_date==	"2022-04-19"|service_date==	"2022-04-20"|service_date==
"2022-04-21")
nTravel_apr <- dplyr::filter(Travel_apr,route_id=="Orange")
```

#1
```{r}
a15 <- dplyr::filter(nTravel_apr,service_date=="2022-04-15")
a15_1 <- dplyr::filter(a15,direction_id==0)
a15_2<- dplyr::filter(a15_1,to_stop_id==min(a15_1$to_stop_id))
a15_3 <- dplyr::filter(a15_2,end_time_sec==min(a15_2$end_time_sec))
a15_4<-dplyr::arrange(a15_3,travel_time_sec)
a15 <- max(a15_4$travel_time_sec)

a16 <- dplyr::filter(nTravel_apr,service_date=="2022-04-16")
a16_1 <- dplyr::filter(a16,direction_id==0)
a16_2<- dplyr::filter(a16_1,to_stop_id==min(a16_1$to_stop_id))
a16_3 <- dplyr::filter(a16_2,end_time_sec==min(a16_2$end_time_sec))
a16_4<-dplyr::arrange(a16_3,travel_time_sec)
a16 <- max(a16_4$travel_time_sec)

a17 <- dplyr::filter(nTravel_apr,service_date=="2022-04-17")
a17_1 <- dplyr::filter(a17,direction_id==0)
a17_2<- dplyr::filter(a17_1,to_stop_id==min(a17_1$to_stop_id))
a17_3 <- dplyr::filter(a17_2,end_time_sec==min(a17_2$end_time_sec))
a17_4<-dplyr::arrange(a17_3,travel_time_sec)
a17 <- max(a17_4$travel_time_sec)

a18 <- dplyr::filter(nTravel_apr,service_date=="2022-04-18")
a18_1 <- dplyr::filter(a18,direction_id==0)
a18_2<- dplyr::filter(a18_1,to_stop_id==min(a18_1$to_stop_id))
a18_3 <- dplyr::filter(a18_2,end_time_sec==min(a18_2$end_time_sec))
a18_4<-dplyr::arrange(a18_3,travel_time_sec)
a18 <- max(a18_4$travel_time_sec)

a19 <- dplyr::filter(nTravel_apr,service_date=="2022-04-19")
a19_1 <- dplyr::filter(a19,direction_id==0)
a19_2<- dplyr::filter(a19_1,to_stop_id==min(a19_1$to_stop_id))
a19_3 <- dplyr::filter(a19_2,end_time_sec==min(a19_2$end_time_sec))
a19_4<-dplyr::arrange(a19_3,travel_time_sec)
a19 <- max(a19_4$travel_time_sec)

a20 <- dplyr::filter(nTravel_apr,service_date=="2022-04-20")
a20_1 <- dplyr::filter(a20,direction_id==0)
a20_2<- dplyr::filter(a20_1,to_stop_id==min(a20_1$to_stop_id))
a20_3 <- dplyr::filter(a20_2,end_time_sec==min(a20_2$end_time_sec))
a20_4<-dplyr::arrange(a20_3,travel_time_sec)
a20 <- max(a20_4$travel_time_sec)

a21 <- dplyr::filter(nTravel_apr,service_date=="2022-04-21")
a21_1 <- dplyr::filter(a21,direction_id==0)
a21_2<- dplyr::filter(a21_1,to_stop_id==min(a21_1$to_stop_id))
a21_3 <- dplyr::filter(a21_2,end_time_sec==min(a21_2$end_time_sec))
a21_4<-dplyr::arrange(a21_3,travel_time_sec)
a21 <- max(a21_4$travel_time_sec)
```

```{r}
total_time_apr<- c(a15,a16,a17,a18,a19,a20,a21)
Apr <- c("4-15","4-16","4-17","4-18","4-19","4-20","4-21")
df_2_Apr <- data.frame(x = Apr, y = total_time_apr)
ggplot(data = df_2_Apr, aes(x = Apr, y = total_time_apr )) + geom_line(aes(x,y,group=1),col="lightblue")+geom_point(aes(x,y),col="purple")
```
# May

```{r}
Travel_may <- dplyr::filter(HRQ2 ,service_date==	"2022-05-15"|service_date==	"2022-05-16"|service_date==	"2022-05-17"|service_date==	"2022-05-18"|service_date==	"2022-05-19"|service_date==	"2022-05-20"|service_date==
"2022-05-21")
nTravel_may <- dplyr::filter(Travel_may,route_id=="Orange")
```

##1
```{r}
ma15 <- dplyr::filter(nTravel_may,service_date=="2022-05-15")
ma15_1 <- dplyr::filter(ma15,direction_id==0)
ma15_2<- dplyr::filter(ma15_1,to_stop_id==min(ma15_1$to_stop_id))
ma15_3 <- dplyr::filter(ma15_2,end_time_sec==min(ma15_2$end_time_sec))
ma15_4<-dplyr::arrange(ma15_3,travel_time_sec)
ma15 <- max(ma15_4$travel_time_sec)

ma16 <- dplyr::filter(nTravel_may,service_date=="2022-05-16")
ma16_1 <- dplyr::filter(ma16,direction_id==0)
ma16_2<- dplyr::filter(ma16_1,to_stop_id==min(ma16_1$to_stop_id))
ma16_3 <- dplyr::filter(ma16_2,end_time_sec==min(ma16_2$end_time_sec))
ma16_4<-dplyr::arrange(ma16_3,travel_time_sec)
ma16 <- max(ma16_4$travel_time_sec)

ma17 <- dplyr::filter(nTravel_may,service_date=="2022-05-17")
ma17_1 <- dplyr::filter(ma17,direction_id==0)
ma17_2<- dplyr::filter(ma17_1,to_stop_id==min(ma17_1$to_stop_id))
ma17_3 <- dplyr::filter(ma17_2,end_time_sec==min(ma17_2$end_time_sec))
ma17_4<-dplyr::arrange(ma17_3,travel_time_sec)
ma17 <- max(ma17_4$travel_time_sec)

ma18 <- dplyr::filter(nTravel_may,service_date=="2022-05-18")
ma18_1 <- dplyr::filter(ma18,direction_id==0)
ma18_2<- dplyr::filter(ma18_1,to_stop_id==min(ma18_1$to_stop_id))
ma18_3 <- dplyr::filter(ma18_2,end_time_sec==min(ma18_2$end_time_sec))
ma18_4<-dplyr::arrange(ma18_3,travel_time_sec)
ma18 <- max(ma18_4$travel_time_sec)

ma19 <- dplyr::filter(nTravel_may,service_date=="2022-05-19")
ma19_1 <- dplyr::filter(ma19,direction_id==0)
ma19_2<- dplyr::filter(ma19_1,to_stop_id==min(ma19_1$to_stop_id))
ma19_3 <- dplyr::filter(ma19_2,end_time_sec==min(ma19_2$end_time_sec))
ma19_4<-dplyr::arrange(ma19_3,travel_time_sec)
ma19 <- max(ma19_4$travel_time_sec)

ma20 <- dplyr::filter(nTravel_may,service_date=="2022-05-20")
ma20_1 <- dplyr::filter(ma20,direction_id==0)
ma20_2<- dplyr::filter(ma20_1,to_stop_id==min(ma20_1$to_stop_id))
ma20_3 <- dplyr::filter(ma20_2,end_time_sec==min(ma20_2$end_time_sec))
ma20_4<-dplyr::arrange(ma20_3,travel_time_sec)
ma20 <- max(ma20_4$travel_time_sec)

ma21 <- dplyr::filter(nTravel_may,service_date=="2022-05-21")
ma21_1 <- dplyr::filter(ma21,direction_id==0)
ma21_2<- dplyr::filter(ma21_1,to_stop_id==min(ma21_1$to_stop_id))
ma21_3 <- dplyr::filter(ma21_2,end_time_sec==min(ma21_2$end_time_sec))
ma21_4<-dplyr::arrange(ma21_3,travel_time_sec)
ma21 <- max(ma21_4$travel_time_sec)
```

```{r}
total_time_may<- c(ma15,ma16,ma17,ma18,ma19,ma20,ma21)
May <- c("5-15","5-16","5-17","5-18","5-19","5-20","5-21")
df_2_May <- data.frame(x = May, y = total_time_may)
ggplot(data = df_2_May, aes(x = May, y = total_time_may )) + geom_line(aes(x,y,group=1),col="lightblue")+geom_point(aes(x,y),col="purple")
```
# June
```{r}
Travel_jun <- dplyr::filter(HRQ2 ,service_date==	"2022-06-15"|service_date==	"2022-06-16"|service_date==	"2022-06-17"|service_date==	"2022-06-18"|service_date==	"2022-06-19"|service_date==	"2022-06-20"|service_date==
"2022-06-21")
nTravel_jun <- dplyr::filter(Travel_jun,route_id=="Orange")
```
#1
```{r}
jun15 <- dplyr::filter(nTravel_jun,service_date=="2022-06-15")
jun15_1 <- dplyr::filter(jun15,direction_id==0)
jun15_2<- dplyr::filter(jun15_1,to_stop_id==min(jun15_1$to_stop_id))
jun15_3 <- dplyr::filter(jun15_2,end_time_sec==min(jun15_2$end_time_sec))
jun15_4<-dplyr::arrange(jun15_3,travel_time_sec)
jun15 <- max(jun15_4$travel_time_sec)

jun16 <- dplyr::filter(nTravel_jun,service_date=="2022-06-16")
jun16_1 <- dplyr::filter(jun16,direction_id==0)
jun16_2<- dplyr::filter(jun16_1,to_stop_id==min(jun16_1$to_stop_id))
jun16_3 <- dplyr::filter(jun16_2,end_time_sec==min(jun16_2$end_time_sec))
jun16_4<-dplyr::arrange(jun16_3,travel_time_sec)
jun16 <- max(jun16_4$travel_time_sec)

jun17 <- dplyr::filter(nTravel_jun,service_date=="2022-06-17")
jun17_1 <- dplyr::filter(jun17,direction_id==0)
jun17_2<- dplyr::filter(jun17_1,to_stop_id==min(jun17_1$to_stop_id))
jun17_3 <- dplyr::filter(jun17_2,end_time_sec==min(jun17_2$end_time_sec))
jun17_4<-dplyr::arrange(jun17_3,travel_time_sec)
jun17 <- max(jun17_4$travel_time_sec)

jun18 <- dplyr::filter(nTravel_jun,service_date=="2022-06-18")
jun18_1 <- dplyr::filter(jun18,direction_id==0)
jun18_2<- dplyr::filter(jun18_1,to_stop_id==min(jun18_1$to_stop_id))
jun18_3 <- dplyr::filter(jun18_2,end_time_sec==min(jun18_2$end_time_sec))
jun18_4<-dplyr::arrange(jun18_3,travel_time_sec)
jun18 <- max(jun18_4$travel_time_sec)

jun19 <- dplyr::filter(nTravel_jun,service_date=="2022-06-19")
jun19_1 <- dplyr::filter(jun19,direction_id==0)
jun19_2<- dplyr::filter(jun19_1,to_stop_id==min(jun19_1$to_stop_id))
jun19_3 <- dplyr::filter(jun19_2,end_time_sec==min(jun19_2$end_time_sec))
jun19_4<-dplyr::arrange(jun19_3,travel_time_sec)
jun19 <- max(jun19_4$travel_time_sec)

jun20 <- dplyr::filter(nTravel_jun,service_date=="2022-06-20")
jun20_1 <- dplyr::filter(jun20,direction_id==0)
jun20_2<- dplyr::filter(jun20_1,to_stop_id==min(jun20_1$to_stop_id))
jun20_3 <- dplyr::filter(jun20_2,end_time_sec==min(jun20_2$end_time_sec))
jun20_4<-dplyr::arrange(jun20_3,travel_time_sec)
jun20 <- max(jun20_4$travel_time_sec)

jun21 <- dplyr::filter(nTravel_jun,service_date=="2022-06-21")
jun21_1 <- dplyr::filter(jun21,direction_id==0)
jun21_2<- dplyr::filter(jun21_1,to_stop_id==min(jun21_1$to_stop_id))
jun21_3 <- dplyr::filter(jun21_2,end_time_sec==min(jun21_2$end_time_sec))
jun21_4<-dplyr::arrange(jun21_3,travel_time_sec)
jun21 <- max(jun21_4$travel_time_sec)
```

```{r}
total_time_jun<- c(jun15,jun16,jun17,jun18,jun19,jun20,jun21)
June <- c("6-15","6-16","6-17","6-18","6-19","6-20","6-21")
df_2_Jun <- data.frame(x = June, y = total_time_jun)
ggplot(data = df_2_Jun, aes(x = June, y = total_time_jun )) + geom_line(aes(x,y,group=1),col="lightblue")+geom_point(aes(x,y),col="purple")
```

# July
```{r}
HRQ3 <- read.csv("D:/360Downloads/TravelTimes_2022/TravelTimes_2022/2022-Q3_HRTravelTimes.csv")
```

```{r}
Travel_jul <- dplyr::filter(HRQ3 ,service_date==	"2022-07-15"|service_date==	"2022-07-16"|service_date==	"2022-07-17"|service_date==	"2022-07-18"|service_date==	"2022-07-19"|service_date==	"2022-07-20"|service_date==
"2022-07-21")
nTravel_jul <- dplyr::filter(Travel_jul,route_id=="Orange")
```

```{r}
jul15 <- dplyr::filter(nTravel_jul,service_date=="2022-07-15")
jul15_1 <- dplyr::filter(jul15,direction_id==0)
jul15_2<- dplyr::filter(jul15_1,to_stop_id==min(jul15_1$to_stop_id))
jul15_3 <- dplyr::filter(jul15_2,end_time_sec==min(jul15_2$end_time_sec))
jul15_4<-dplyr::arrange(jul15_3,travel_time_sec)
jul15 <- max(jul15_4$travel_time_sec)

jul16 <- dplyr::filter(nTravel_jul,service_date=="2022-07-16")
jul16_1 <- dplyr::filter(jul16,direction_id==0)
jul16_2<- dplyr::filter(jul16_1,to_stop_id==min(jul16_1$to_stop_id))
jul16_3 <- dplyr::filter(jul16_2,end_time_sec==min(jul16_2$end_time_sec))
jul16_4<-dplyr::arrange(jul16_3,travel_time_sec)
jul16 <- max(jul16_4$travel_time_sec)

jul17 <- dplyr::filter(nTravel_jul,service_date=="2022-07-17")
jul17_1 <- dplyr::filter(jul17,direction_id==0)
jul17_2<- dplyr::filter(jul17_1,to_stop_id==min(jul17_1$to_stop_id))
jul17_3 <- dplyr::filter(jul17_2,end_time_sec==min(jul17_2$end_time_sec))
jul17_4<-dplyr::arrange(jul17_3,travel_time_sec)
jul17 <- max(jul17_4$travel_time_sec)

jul18 <- dplyr::filter(nTravel_jul,service_date=="2022-07-18")
jul18_1 <- dplyr::filter(jul18,direction_id==0)
jul18_2<- dplyr::filter(jul18_1,to_stop_id==min(jul18_1$to_stop_id))
jul18_3 <- dplyr::filter(jul18_2,end_time_sec==min(jul18_2$end_time_sec))
jul18_4<-dplyr::arrange(jul18_3,travel_time_sec)
jul18 <- max(jul18_4$travel_time_sec)

jul19 <- dplyr::filter(nTravel_jul,service_date=="2022-07-19")
jul19_1 <- dplyr::filter(jul19,direction_id==0)
jul19_2<- dplyr::filter(jul19_1,to_stop_id==min(jul19_1$to_stop_id))
jul19_3 <- dplyr::filter(jul19_2,end_time_sec==min(jul19_2$end_time_sec))
jul19_4<-dplyr::arrange(jul19_3,travel_time_sec)
jul19 <- max(jul19_4$travel_time_sec)

jul20 <- dplyr::filter(nTravel_jul,service_date=="2022-07-20")
jul20_1 <- dplyr::filter(jul20,direction_id==0)
jul20_2<- dplyr::filter(jul20_1,to_stop_id==min(jul20_1$to_stop_id))
jul20_3 <- dplyr::filter(jul20_2,end_time_sec==min(jul20_2$end_time_sec))
jul20_4<-dplyr::arrange(jul20_3,travel_time_sec)
jul20 <- max(jul20_4$travel_time_sec)

jul21 <- dplyr::filter(nTravel_jul,service_date=="2022-07-21")
jul21_1 <- dplyr::filter(jul21,direction_id==0)
jul21_2<- dplyr::filter(jul21_1,to_stop_id==min(jul21_1$to_stop_id))
jul21_3 <- dplyr::filter(jul21_2,end_time_sec==min(jul21_2$end_time_sec))
jul21_4<-dplyr::arrange(jul21_3,travel_time_sec)
jul21 <- max(jul21_4$travel_time_sec)
```

```{r}
total_time_jul<- c(jul15,jul16,jul17,jul18,jul19,jul20,jul21)
July <- c("7-15","7-16","7-17","7-18","7-19","7-20","7-21")
df_2_Jul <- data.frame(x = July, y = total_time_jul)
ggplot(data = df_2_Jul, aes(x = July, y = total_time_jul )) + geom_line(aes(x,y,group=1),col="lightblue")+geom_point(aes(x,y),col="purple")
```

# August

```{r}
Travel_aug <- dplyr::filter(HRQ3 ,service_date==	"2022-08-15"|service_date==	"2022-08-16"|service_date==	"2022-08-17"|service_date==	"2022-08-18"|service_date==	"2022-08-19"|service_date==	"2022-08-20"|service_date==
"2022-08-21")
nTravel_aug <- dplyr::filter(Travel_aug,route_id=="Orange")
```
#1
```{r}
aug15 <- dplyr::filter(nTravel_aug,service_date=="2022-08-15")
aug15_1 <- dplyr::filter(aug15,direction_id==0)
aug15_2<- dplyr::filter(aug15_1,to_stop_id==min(aug15_1$to_stop_id))
aug15_3 <- dplyr::filter(aug15_2,end_time_sec==min(aug15_2$end_time_sec))
aug15_4<-dplyr::arrange(aug15_3,travel_time_sec)
aug15 <- max(aug15_4$travel_time_sec)

aug16 <- dplyr::filter(nTravel_aug,service_date=="2022-08-16")
aug16_1 <- dplyr::filter(aug16,direction_id==0)
aug16_2<- dplyr::filter(aug16_1,to_stop_id==min(aug16_1$to_stop_id))
aug16_3 <- dplyr::filter(aug16_2,end_time_sec==min(aug16_2$end_time_sec))
aug16_4<-dplyr::arrange(aug16_3,travel_time_sec)
aug16 <- max(aug16_4$travel_time_sec)

aug17 <- dplyr::filter(nTravel_aug,service_date=="2022-08-17")
aug17_1 <- dplyr::filter(aug17,direction_id==0)
aug17_2<- dplyr::filter(aug17_1,to_stop_id==min(aug17_1$to_stop_id))
aug17_3 <- dplyr::filter(aug17_2,end_time_sec==min(aug17_2$end_time_sec))
aug17_4<-dplyr::arrange(aug17_3,travel_time_sec)
aug17 <- max(aug17_4$travel_time_sec)

aug18 <- dplyr::filter(nTravel_aug,service_date=="2022-08-18")
aug18_1 <- dplyr::filter(aug18,direction_id==0)
aug18_2<- dplyr::filter(aug18_1,to_stop_id==min(aug18_1$to_stop_id))
aug18_3 <- dplyr::filter(aug18_2,end_time_sec==min(aug18_2$end_time_sec))
aug18_4<-dplyr::arrange(aug18_3,travel_time_sec)
aug18 <- max(aug18_4$travel_time_sec)

aug19 <- dplyr::filter(nTravel_aug,service_date=="2022-08-19")
aug19_1 <- dplyr::filter(aug19,direction_id==0)
aug19_2<- dplyr::filter(aug19_1,to_stop_id==min(aug19_1$to_stop_id))
aug19_3 <- dplyr::filter(aug19_2,end_time_sec==min(aug19_2$end_time_sec))
aug19_4<-dplyr::arrange(aug19_3,travel_time_sec)
aug19 <- max(aug19_4$travel_time_sec)

aug20 <- dplyr::filter(nTravel_aug,service_date=="2022-08-20")
aug20_1 <- dplyr::filter(aug20,direction_id==0)
aug20_2<- dplyr::filter(aug20_1,to_stop_id==min(aug20_1$to_stop_id))
aug20_3 <- dplyr::filter(aug20_2,end_time_sec==min(aug20_2$end_time_sec))
aug20_4<-dplyr::arrange(aug20_3,travel_time_sec)
aug20 <- max(aug20_4$travel_time_sec)

aug21 <- dplyr::filter(nTravel_aug,service_date=="2022-08-21")
aug21_1 <- dplyr::filter(aug21,direction_id==0)
aug21_2<- dplyr::filter(aug21_1,to_stop_id==min(aug21_1$to_stop_id))
aug21_3 <- dplyr::filter(aug21_2,end_time_sec==min(aug21_2$end_time_sec))
aug21_4<-dplyr::arrange(aug21_3,travel_time_sec)
aug21 <- max(aug21_4$travel_time_sec)
```

```{r}
total_time_aug<- c(aug15,aug16,aug17,aug18,aug19,aug20,aug21)
August <- c("8-15","8-16","8-17","8-18","8-19","8-20","8-21")
df_2_aug <- data.frame(x = August, y = total_time_aug)
ggplot(data = df_2_aug, aes(x = August, y = total_time_aug )) + geom_line(aes(x,y,group=1),col="lightblue")+geom_point(aes(x,y),col="purple")
```

# September
```{r}
Travel_sep <- dplyr::filter(HRQ3 ,service_date==	"2022-09-15"|service_date==	"2022-09-16"|service_date==	"2022-09-17"|service_date==	"2022-09-18"|service_date==	"2022-09-19"|service_date==	"2022-09-20"|service_date==
"2022-09-21")
nTravel_sep <- dplyr::filter(Travel_sep,route_id=="Orange")
```
#1
```{r}
s15 <- dplyr::filter(nTravel_sep,service_date=="2022-09-15")
s15_1 <- dplyr::filter(s15,direction_id==0)
s15_2<- dplyr::filter(s15_1,to_stop_id==min(s15_1$to_stop_id))
s15_3 <- dplyr::filter(s15_2,end_time_sec==min(s15_2$end_time_sec))
s15_4<-dplyr::arrange(s15_3,travel_time_sec)
s15 <- max(s15_4$travel_time_sec)

s16 <- dplyr::filter(nTravel_sep,service_date=="2022-09-16")
s16_1 <- dplyr::filter(s16,direction_id==0)
s16_2<- dplyr::filter(s16_1,to_stop_id==min(s16_1$to_stop_id))
s16_3 <- dplyr::filter(s16_2,end_time_sec==min(s16_2$end_time_sec))
s16_4<-dplyr::arrange(s16_3,travel_time_sec)
s16 <- max(s16_4$travel_time_sec)

s17 <- dplyr::filter(nTravel_sep,service_date=="2022-09-17")
s17_1 <- dplyr::filter(s17,direction_id==0)
s17_2<- dplyr::filter(s17_1,to_stop_id==min(s17_1$to_stop_id))
s17_3 <- dplyr::filter(s17_2,end_time_sec==min(s17_2$end_time_sec))
s17_4<-dplyr::arrange(s17_3,travel_time_sec)
s17 <- max(s17_4$travel_time_sec)

s18 <- dplyr::filter(nTravel_sep,service_date=="2022-09-18")
s18_1 <- dplyr::filter(s18,direction_id==0)
s18_2<- dplyr::filter(s18_1,to_stop_id==min(s18_1$to_stop_id))
s18_3 <- dplyr::filter(s18_2,end_time_sec==min(s18_2$end_time_sec))
s18_4<-dplyr::arrange(s18_3,travel_time_sec)
s18 <- max(s18_4$travel_time_sec)

s19 <- dplyr::filter(nTravel_sep,service_date=="2022-09-19")
s19_1 <- dplyr::filter(s19,direction_id==0)
s19_2<- dplyr::filter(s19,to_stop_id==min(s19_1$to_stop_id))
s19_3 <- dplyr::filter(s19_2,end_time_sec==min(s19_2$end_time_sec))
s19_4<-dplyr::arrange(s19_3,travel_time_sec)
s19 <- max(s19_4$travel_time_sec)

s20 <- dplyr::filter(nTravel_sep,service_date=="2022-09-20")
s20_1 <- dplyr::filter(s20,direction_id==0)
s20_2<- dplyr::filter(s20_1,to_stop_id==min(s20_1$to_stop_id))
s20_3 <- dplyr::filter(s20_2,end_time_sec==min(s20_2$end_time_sec))
s20_4<-dplyr::arrange(s20_3,travel_time_sec)
s20 <- max(s20_4$travel_time_sec)

s21 <- dplyr::filter(nTravel_sep,service_date=="2022-09-21")
s21_1 <- dplyr::filter(s21,direction_id==0)
s21_2<- dplyr::filter(s21_1,to_stop_id==min(s21_1$to_stop_id))
s21_3 <- dplyr::filter(s21_2,end_time_sec==min(s21_2$end_time_sec))
s21_4<-dplyr::arrange(s21_3,travel_time_sec)
s21 <- max(s21_4$travel_time_sec)
```

```{r}
total_time_sep<- c(s15,s16,s17,s18,s19,s20,s21)
September <- c("9-15","9-16","9-17","9-18","9-19","9-20","9-21")
df_2_sep <- data.frame(x = September, y = total_time_sep)
ggplot(data = df_2_sep, aes(x = September, y = total_time_sep )) + geom_line(aes(x,y,group=1),col="lightblue")+geom_point(aes(x,y),col="purple")
```

